import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"
import { GetStaticProps, GetStaticPaths, GetServerSideProps } from "next"

interface Dog {
  Name?: string
  Age?: string | number
}
interface HomeProperty {
  str1?: string
  str2?: string
  dogList: Dog[]
}

const Home: NextPage<HomeProperty> = ({ str1, str2, dogList }) => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* map arrayList to JSX.element */}
      {dogList.map((value: Dog, index) => (
        <h2>good</h2>
      ))}

      {
        <div>
          <h5>{str1}</h5>
          <h5>{str2}</h5>
        </div>
      }

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

// Home.getInitialProps = async ({}) => {
//   const res = await fetch("http://localhost:3000/")
//   const dogs = await res.json()
//   const str1 = "good"
//   const str2 = "bad"
//   //return multiple parameter
//   return { str1, str2, dogs }
// }

export const getStaticProps: GetStaticProps = async () => {
  const response = await fetch("http://localhost:3000/")
  const dogs = await response.json()

  let index: number = 0
  let dogList: Dog[] = [];
  //loop for firebase [{},{},{}] list
  while (dogs[index] != null) {
    dogList.push(dogs[index])
    // console.log(dogList[index])
    index++
  }

  const str1 = "good"
  const str2 = "bad"
  //return multiple parameter
  return {
    props: {
      dogList,
      str1,
      str2,
    },
  }
}

export default Home
